services:
  downtime-server:
    image: cosmtrek/air
    container_name: downtime-server
    restart: always
    working_dir: /utils
    ports:
      - "8080:8080"
    volumes:
      - ./:/utils
    command: ["-c", "/utils/cmd/downtime-server/air.toml"]

  doh2dns:
    image: cosmtrek/doh2dns
    container_name: doh2dns
    restart: always
    ports:
      - "8080:8080/tcp"
    command: ["-c", "/utils/cmd/doh2dns/air.toml"]