services:
  downtime-server:
    image: cosmtrek/air
    restart: always
    working_dir: /utils
    ports:
      - "8080:8080"
    volumes:
      - ./:/utils
    command: ["-c", "/utils/cmd/downtime-server/air.toml"]